const field=(id,label,type,api=id,required=true,extra={})=>({id,label,type,api,required,...extra});
const prompt=(label='描述你想生成的内容',api='prompt',required=true)=>field('prompt',label,'textarea',api,required);
const media=(id,label,type,api=id,required=true,extra={})=>field(id,label,type,api,required,extra);
const select=(id,label,values,api=id,value=values[0],extra={})=>({id,label,type:'select',values,api,value,...extra});
const number=(id,label,value,api=id,extra={})=>({id,label,type:'number',value,api,...extra});
const text=(id,label,value='',api=id,extra={})=>({id,label,type:'text',value,api,...extra});
const toggle=(id,label,value=false,api=id,extra={})=>({id,label,type:'boolean',value,api,...extra});
const dynamic={unit:'dynamic',label:'提交后按模型与素材确认'};
const perSecond=rates=>({unit:'credits_per_second',byResolution:rates});
const model=(id,group,label,short,endpoint,outputKind,inputs,options=[],extra={})=>({id,group,label,short,endpoint,outputKind,inputs,options,contentProfiles:['standard','mature-audience'],pricing:dynamic,status:'active',...extra});

export default [
  model('lipsync-v1','数字人与口型','LipSync 1.0','视频与新音轨自动对口型','/api/async/lipsync','video',[media('video','原始视频','video','srcVideoUrl'),media('audio','驱动音频','audio','audioUrl')],[number('width','输出宽度（0 为原尺寸）',0,'video_width',{container:'videoParams'}),number('height','输出高度（0 为原尺寸）',0,'video_height',{container:'videoParams'}),toggle('enhance','启用视频增强',false,'video_enhance',{container:'videoParams'})]),
  model('lipsync-2','数字人与口型','LipSync 2.0','更自然的口型与可选人声分离','/api/async/lipsync/2.0','video',[media('video','原始视频','video','srcVideoUrl'),media('audio','原始音频','audio','audioUrl'),media('vocalAudio','纯人声音轨（可选）','audio','vocalAudioUrl',false)],[number('width','输出宽度（0 为原尺寸）',0,'video_width',{container:'videoParams'}),number('height','输出高度（0 为原尺寸）',0,'video_height',{container:'videoParams'}),select('enhance','视频增强',['1','0'],'video_enhance','1',{container:'videoParams'}),text('fps','帧率（可选）','','fps')]),
  model('dreamavatar-3-fast','数字人与口型','DreamAvatar 3.0 Fast','图片与音频生成数字人口播','/api/async/dreamavatar/image_to_video/3.0fast','video',[media('image','角色图片','image'),media('audio','讲解音频','audio'),prompt('角色表现描述')],[select('resolution','清晰度',['480p','720p'])],{pricing:{unit:'credits_per_second',byResolution:{'480p':2,'720p':4},requiresMediaDuration:true}}),
  model('dreamact-2-1','数字人与口型','DreamAct 2.1','让角色跟随驱动视频动作','/api/async/wan/dreamact/2.1','video',[media('video','驱动视频','video'),media('images','角色参考图片','image','images',true,{multiple:true,max:4})],[select('resolution','清晰度',['480P','720P']),select('taskMode','任务模式',['replace_body','pose2v']),select('qualityMode','质量模式',['base','high']),number('seed','随机种子',42)]),
  model('flux-text-image','图片生成','Flux 文生图','从文字生成图片','/api/async/flux_text2image','image',[prompt('图片描述')],[number('width','宽度',1024),number('height','高度',1024),number('num','生成数量',1,'num',{min:1,max:10}),number('seed','随机种子',-1)]),
  model('flux-image-image','图片生成','Flux 图生图','参考图片进行风格与内容变换','/api/async/flux_image2image','image',[media('image','参考图片','image','imageUrl'),prompt('修改描述')],[number('width','宽度',1024),number('height','高度',1024),number('num','生成数量',1,'num',{min:1,max:10}),number('seed','随机种子',-1)]),
  model('dreamimage-2','图片生成','DreamImage 2.0','自然语言编辑原图','/api/async/dreamimage_2.0','image',[media('image','需要编辑的图片','image'),prompt('修改描述')],[],{pricing:{unit:'credits_per_task',flat:10,label:'10 credits'}}),
  model('image-colorize','图片编辑','黑白照片上色','为包含人物的黑白照片着色','/api/async/colorize','image',[media('image','黑白照片','image','url')]),
  model('image-enhance','图片编辑','图片增强','提升清晰度与画质','/api/async/enhance','image',[media('image','需要增强的图片','image','imageUrl')]),
  model('image-outpainting','图片编辑','智能扩图','向四周延展画面','/api/async/outpainting','image',[media('image','原始图片','image','url')],[number('left','向左扩展像素',0,'left',{container:'outPaintSize'}),number('right','向右扩展像素',0,'right',{container:'outPaintSize'}),number('top','向上扩展像素',0,'top',{container:'outPaintSize'}),number('bottom','向下扩展像素',0,'bottom',{container:'outPaintSize'})]),
  model('image-swap-face','图片编辑','图片换脸','替换目标图片中的人脸','/api/async/swap_face','image',[media('image','目标图片','image','url'),media('face','来源人脸','image','faceImgUrl')]),
  model('image-remove-bg','图片编辑','图片去背景','输出透明背景主体','/api/async/remove_background','image',[media('image','原始图片','image','url')]),
  model('virtual-try-on','图片编辑','AI 虚拟试衣','将服装自然穿到模特身上','/api/async/tryon_clothes','image',[media('modelImage','模特图片','image','modelImage'),media('upper','上装（可选）','image','upperClothes',false),media('lower','下装（可选）','image','lowerClothes',false),media('overall','连体服装（可选）','image','overallClothes',false),prompt('补充描述','prompt',false)],[toggle('enableShoes','生成鞋子',false),number('width','宽度',768),number('height','高度',1378)]),
  model('wan-text-video','视频生成','Wan 2.1 文生视频','从文字生成视频','/api/async/wan/text_to_video/2.1','video',[prompt('视频描述')],[select('resolution','清晰度',['480p','720p'])]),
  model('wan-image-video','视频生成','Wan 2.1 图生视频','让一张图片动起来','/api/async/wan/image_to_video/2.1','video',[media('image','首帧图片','image'),prompt('运动描述')],[select('resolution','清晰度',['480p','720p'])]),
  model('wan-head-tail','视频生成','Wan 2.1 首尾帧','生成两张图片之间的转场','/api/async/wan/head_tail_to_video/2.1','video',[media('first','首帧图片','image','firstImage'),media('last','尾帧图片','image','lastImage'),prompt('转场描述')]),
  model('dreamvideo-3-text','视频生成','DreamVideo 3.0 文生视频','3–15 秒可控画幅视频','/api/async/dreamvideo_3.0/text_to_video','video',[prompt('视频描述')],[select('resolution','清晰度',['480P','720P']),select('duration','时长',[3,5,8,10,15],'duration',5),select('aspectRatio','画幅',['auto','16:9','9:16','1:1','4:3','3:4']),number('seed','随机种子',42)],{pricing:perSecond({'480P':2,'720P':4})}),
  model('dreamvideo-3-image','视频生成','DreamVideo 3.0 图生视频','支持单图动画与首尾帧','/api/async/dreamvideo_3.0/image_to_video','video',[media('images','参考图片（最多 2 张）','image','images',true,{multiple:true,max:2}),prompt('运动与场景描述')],[select('resolution','清晰度',['480P','720P']),select('duration','时长',[3,5,8,10,15],'duration',5),select('aspectRatio','画幅',['auto','16:9','9:16','1:1','4:3','3:4']),number('seed','随机种子',42)],{pricing:perSecond({'480P':2,'720P':4})}),
  model('video-swap-face','视频编辑','视频换脸','替换视频中的人物面部','/api/async/swap_face_for_video','video',[media('video','原始视频','video','srcVideoUrl'),media('face','来源人脸','image','srcImgUrl')]),
  model('video-matting','视频编辑','视频抠像','提取人物与 Alpha 通道','/api/async/image_matting_process_video','video',[media('video','原始视频','video','srcFileUrl')],[text('bitRate','目标码率（可选）','','bitRate'),toggle('removeColorSpill','去除边缘溢色',false)]),
  model('video-composite','视频编辑','视频背景合成','将抠像结果与新背景合成','/api/async/image_matting_composite_video','video',[media('video','原始视频','video','srcFileUrl'),field('alpha','Alpha 视频 URL','text','mattingAlphaFileUrl')],[select('backgroundType','背景类型',['color','image','video']),text('backgroundColor','背景颜色（如 232d84）','232d84'),text('backgroundUrl','背景图片或视频 URL（可选）','')]),
  model('video-watermark','视频编辑','视频水印移除','智能移除视频水印','/api/async/video_watermark_remover','video',[media('video','原始视频','video'),prompt('处理提示（可选）','prompt',false)],[number('seed','随机种子',-1)]),
  model('video-enhance','视频编辑','视频画质增强','超分辨率与细节增强','/api/async/video_super_resolution','video',[media('video','原始视频','video','srcVideoUrl')]),
  model('video-translate','视频翻译','Video Translate 2.0','翻译语音并可同步口型','/api/async/video_translate/2.0','video',[media('video','需要翻译的视频','video','videoUrl')],[select('sourceLanguage','源语言',['en','zh','es']),select('targetLanguage','目标语言',['zh','en','es']),toggle('enableLipSync','同步口型',true)]),
  model('seedance-2-5','字节模型','Seedance 2.5','多模态视频生成','/api/async/seedance_2.5','video',[prompt('视频描述'),media('images','参考图片（可选）','image','images',false,{multiple:true,max:9}),media('videos','参考视频（可选）','video','videos',false,{multiple:true,max:10}),media('audios','参考音频（可选）','audio','audios',false,{multiple:true,max:3}),media('imageUrl','首帧图片（可选）','image','imageUrl',false),media('endImageUrl','尾帧图片（可选）','image','endImageUrl',false)],[select('resolution','清晰度',['480p','720p','1080p']),number('duration','时长（秒）',5,'duration',{min:4,max:30}),select('ratio','画幅',['adaptive','16:9','9:16','1:1']),number('seed','随机种子',-1),toggle('generateAudio','生成音频',false)],{fixed:{model:'seedance-2.5'}}),
  model('seedance-2','字节模型','Seedance 2.0','最高支持 4K 的多模态视频','/api/async/seedance_2.0','video',[prompt('视频描述'),media('images','参考图片（可选）','image','images',false,{multiple:true,max:9}),media('videos','参考视频（可选）','video','videos',false,{multiple:true,max:3}),media('audios','参考音频（可选）','audio','audios',false,{multiple:true,max:3}),media('imageUrl','首帧图片（可选）','image','imageUrl',false),media('endImageUrl','尾帧图片（可选）','image','endImageUrl',false)],[select('resolution','清晰度',['480p','720p','1080p','4k']),number('duration','时长（秒）',5,'duration',{min:4,max:15}),select('ratio','画幅',['adaptive','16:9','9:16','1:1']),number('seed','随机种子',-1),toggle('generateAudio','生成音频',false)],{fixed:{model:'seedance-2.0'}}),
  model('seedance-2-mini','字节模型','Seedance 2.0 Mini','更低成本的视频生成','/api/async/seedance_2.0','video',[prompt('视频描述'),media('images','参考图片（可选）','image','images',false,{multiple:true,max:9}),media('videos','参考视频（可选）','video','videos',false,{multiple:true,max:3}),media('audios','参考音频（可选）','audio','audios',false,{multiple:true,max:3}),media('imageUrl','首帧图片（可选）','image','imageUrl',false),media('endImageUrl','尾帧图片（可选）','image','endImageUrl',false)],[select('resolution','清晰度',['480p','720p']),number('duration','时长（秒）',5,'duration',{min:4,max:15}),select('ratio','画幅',['adaptive','16:9','9:16','1:1']),number('seed','随机种子',-1),toggle('generateAudio','生成音频',false)],{fixed:{model:'seedance-2.0-mini'}}),
  model('seedance-2-fast','字节模型','Seedance 2.0 Fast','快速视频生成','/api/async/seedance_2.0','video',[prompt('视频描述')],[select('resolution','清晰度',['480p','720p']),number('duration','时长（秒）',5,'duration',{min:4,max:15}),select('ratio','画幅',['adaptive','16:9','9:16','1:1','3:4','4:3','21:9']),number('seed','随机种子',-1),toggle('generateAudio','生成音频',false)],{fixed:{model:'seedance-2.0-fast'}}),
  model('seedance-1-5-pro','字节模型','Seedance 1.5 Pro','专业文生视频','/api/async/seedance_1.5_pro','video',[prompt('视频描述')],[select('resolution','清晰度',['480p','720p','1080p']),select('ratio','画幅',['adaptive','16:9','9:16','1:1','3:4','4:3']),number('seed','随机种子',-1),toggle('generateAudio','生成音频',false)],{fixed:{model:'seedance-1.5-pro'}}),
  model('seedream','字节模型','Seedream','4.0–5.0 多版本图片生成','/api/async/seedream','image',[prompt('图片描述'),media('image','参考图片（可选）','image','image',false,{multiple:true,max:10})],[select('model','模型版本',['seedream-5.0-pro','seedream-5.0-lite','seedream-4.5','seedream-4.0']),select('size','输出尺寸',['1K','1.5K','2K']),number('seed','随机种子',-1)]),
  model('nano-banana-2','Google 模型','Nano Banana 2','Gemini 3.1 Flash 图片生成','/api/async/google_gemini_image','image',[prompt('图片描述','text'),media('images','参考图片（可选）','image','images',false,{multiple:true,max:8})],[select('imageSize','输出尺寸',['512','1K','2K','4K']),select('aspectRatio','画幅',['1:1','16:9','9:16','4:3','3:4'])],{fixed:{model:'gemini-3.1-flash-image-preview'}}),
  model('nano-banana-pro','Google 模型','Nano Banana Pro','Gemini 3 Pro 高质量图片生成','/api/async/google_gemini_image','image',[prompt('图片描述','text'),media('images','参考图片（可选）','image','images',false,{multiple:true,max:8})],[select('imageSize','输出尺寸',['1K','2K']),select('aspectRatio','画幅',['1:1','16:9','9:16','4:3','3:4'])],{fixed:{model:'gemini-3-pro-image-preview'}}),
  model('gpt-image-2','OpenAI 模型','GPT Image 2','OpenAI 图片生成与编辑','/api/async/gpt_image','image',[prompt('图片描述'),media('images','参考图片（可选）','image','images',false,{multiple:true,max:4})],[number('width','宽度',1024),number('height','高度',1024),select('quality','质量',['low','medium','high']),number('n','生成数量',1,'n',{min:1,max:10})]),
  model('gpt-image-2-5-flare-text','OpenAI 模型','GPT Image 2.5 Flare 文生图','更快的 GPT Image 2.5','/api/async/gpt_image_2.5/flare/text_to_image','image',[prompt('图片描述')],[number('width','宽度',1024),number('height','高度',1024),select('quality','质量',['low','medium','high','xhigh','max']),number('n','生成数量',1,'n',{min:1,max:10})]),
  model('gpt-image-2-5-flare-edit','OpenAI 模型','GPT Image 2.5 Flare 图生图','参考图片快速编辑','/api/async/gpt_image_2.5/flare/image_to_image','image',[prompt('修改描述'),media('images','参考图片（1–4 张）','image','images',true,{multiple:true,max:4})],[number('width','宽度',1024),number('height','高度',1024),select('quality','质量',['low','medium','high','xhigh','max']),number('n','生成数量',1,'n',{min:1,max:10})]),
  model('gpt-image-2-5-sunburst-text','OpenAI 模型','GPT Image 2.5 Sunburst 文生图','更注重复杂细节','/api/async/gpt_image_2.5/sunburst/text_to_image','image',[prompt('图片描述')],[number('width','宽度',1024),number('height','高度',1024),select('quality','质量',['low','medium','high','xhigh','max']),number('n','生成数量',1,'n',{min:1,max:10})]),
  model('gpt-image-2-5-sunburst-edit','OpenAI 模型','GPT Image 2.5 Sunburst 图生图','参考图片精细编辑','/api/async/gpt_image_2.5/sunburst/image_to_image','image',[prompt('修改描述'),media('images','参考图片（1–4 张）','image','images',true,{multiple:true,max:4})],[number('width','宽度',1024),number('height','高度',1024),select('quality','质量',['low','medium','high','xhigh','max']),number('n','生成数量',1,'n',{min:1,max:10})]),
  model('voice-clone','语音','声音克隆','从音频样本创建克隆音色','/api/async/voice_clone','data',[media('audio','声音样本','audio','voiceUrl')]),
  model('tts-clone','语音','克隆音色 TTS','使用已克隆音色合成语音','/api/async/do_tts_clone','audio',[field('cloneId','克隆音色 ID','text','cloneId'),field('text','需要朗读的文字','textarea','text')],[text('language','语言代码','zh-CN','lan')]),
  model('tts-common','语音','标准音色 TTS','使用标准音色合成语音','/api/async/do_tts_common','audio',[field('audioId','标准音色 ID','text','audioId'),field('text','需要朗读的文字','textarea','text')],[text('language','语言代码','zh-CN','lan')]),
  model('tts-pro','语音','高级音色 TTS','使用 Pro 音色合成语音','/api/async/do_tts_pro','audio',[field('audioId','Pro 音色 ID','text','audioId'),field('text','需要朗读的文字','textarea','text')],[text('language','语言代码','zh-CN','lan')]),
  model('voice-list','语音','音色目录','浏览标准与 Pro 音色（辅助能力）',null,'data',[],[select('type','音色类型',['all','common','pro']),text('language','语言筛选（可选）',''),select('timbre','音色性别',['all','female','male'])],{utility:'voice-catalog',pricing:{unit:'free',label:'免费查询'}})
];
