const field=(id,label,type,api=id,required=true,extra={})=>({id,label,type,api,required,...extra});
const prompt=(label='Describe what you want to create',api='prompt',required=true)=>field('prompt',label,'textarea',api,required);
const media=(id,label,type,api=id,required=true,extra={})=>field(id,label,type,api,required,extra);
const select=(id,label,values,api=id,value=values[0],extra={})=>({id,label,type:'select',values,api,value,...extra});
const number=(id,label,value,api=id,extra={})=>({id,label,type:'number',value,api,...extra});
const text=(id,label,value='',api=id,extra={})=>({id,label,type:'text',value,api,...extra});
const toggle=(id,label,value=false,api=id,extra={})=>({id,label,type:'boolean',value,api,...extra});
const dynamic={unit:'dynamic',label:'Usage confirmed after submission'};
const perSecond=rates=>({unit:'credits_per_second',byResolution:rates});
const model=(id,group,label,short,endpoint,outputKind,inputs,options=[],extra={})=>({id,group,label,short,endpoint,outputKind,inputs,options,contentProfiles:['standard','mature-audience'],pricing:dynamic,status:'active',...extra});

export default [
  model('lipsync-v1','Avatars and lip sync','LipSync 1.0','Sync a video to a new audio track','/api/async/lipsync','video',[media('video','Source video','video','srcVideoUrl'),media('audio','Driving audio','audio','audioUrl')],[number('width','Output width (0 = original)',0,'video_width',{container:'videoParams'}),number('height','Output height (0 = original)',0,'video_height',{container:'videoParams'}),toggle('enhance','Enhance video',false,'video_enhance',{container:'videoParams'})]),
  model('lipsync-2','Avatars and lip sync','LipSync 2.0','Natural lip sync with optional vocal separation','/api/async/lipsync/2.0','video',[media('video','Source video','video','srcVideoUrl'),media('audio','Source audio','audio','audioUrl'),media('vocalAudio','Isolated vocal track (optional)','audio','vocalAudioUrl',false)],[number('width','Output width (0 = original)',0,'video_width',{container:'videoParams'}),number('height','Output height (0 = original)',0,'video_height',{container:'videoParams'}),select('enhance','Video enhancement',['1','0'],'video_enhance','1',{container:'videoParams'}),text('fps','Frame rate (optional)','','fps')]),
  model('dreamavatar-3-fast','Avatars and lip sync','DreamAvatar 3.0 Fast','Create a talking avatar from an image and audio','/api/async/dreamavatar/image_to_video/3.0fast','video',[media('image','Character image','image'),media('audio','Narration audio','audio'),prompt('Performance prompt')],[select('resolution','Resolution',['480p','720p'])],{pricing:{unit:'credits_per_second',byResolution:{'480p':2,'720p':4},requiresMediaDuration:true}}),
  model('dreamact-2-1','Avatars and lip sync','DreamAct 2.1','Transfer motion from a driving video to a character','/api/async/wan/dreamact/2.1','video',[media('video','Driving video','video'),media('images','Character reference image','image','images',true,{multiple:true,max:4})],[select('resolution','Resolution',['480P','720P']),select('taskMode','Task mode',['replace_body','pose2v']),select('qualityMode','Quality mode',['base','high']),number('seed','Seed',42)]),
  model('flux-text-image','Image generation','Flux','Generate images from text','/api/async/flux_text2image','image',[prompt('Image prompt')],[number('width','Width',1024),number('height','Height',1024),number('num','Output count',1,'num',{min:1,max:10}),number('seed','Seed',-1)]),
  model('flux-image-image','Image generation','Flux','Transform the style and content of a reference image','/api/async/flux_image2image','image',[media('image','Reference image','image','imageUrl'),prompt('Editing prompt')],[number('width','Width',1024),number('height','Height',1024),number('num','Output count',1,'num',{min:1,max:10}),number('seed','Seed',-1)]),
  model('dreamimage-2','Image generation','DreamImage 2.0','Edit an image with natural language','/api/async/dreamimage_2.0','image',[media('image','Image to edit','image'),prompt('Editing prompt')],[],{pricing:{unit:'credits_per_task',flat:10,label:'10 credits'}}),
  model('image-colorize','Image editing','Colorize','Colorize black-and-white portrait photos','/api/async/colorize','image',[media('image','Black-and-white photo','image','url')]),
  model('image-enhance','Image editing','Enhance','Improve image clarity and quality','/api/async/enhance','image',[media('image','Image to enhance','image','imageUrl')]),
  model('image-outpainting','Image editing','Outpainting','Extend an image beyond its borders','/api/async/outpainting','image',[media('image','Source image','image','url')],[number('left','Extend left (pixels)',0,'left',{container:'outPaintSize'}),number('right','Extend right (pixels)',0,'right',{container:'outPaintSize'}),number('top','Extend top (pixels)',0,'top',{container:'outPaintSize'}),number('bottom','Extend bottom (pixels)',0,'bottom',{container:'outPaintSize'})]),
  model('image-swap-face','Image editing','Swapface','Replace a face in an image','/api/async/swap_face','image',[media('image','Target image','image','url'),media('face','Source face','image','faceImgUrl')]),
  model('image-remove-bg','Image editing','Remove Background','Remove the background and keep the subject','/api/async/remove_background','image',[media('image','Source image','image','url')]),
  model('virtual-try-on','Image editing','Virtual Try-on','Apply clothing to a model image','/api/async/tryon_clothes','image',[media('modelImage','Model image','image','modelImage'),media('upper','Upper garment (optional)','image','upperClothes',false),media('lower','Lower garment (optional)','image','lowerClothes',false),media('overall','Full outfit (optional)','image','overallClothes',false),prompt('Additional prompt','prompt',false)],[toggle('enableShoes','Generate shoes',false),number('width','Width',768),number('height','Height',1378)]),
  model('wan-text-video','Video generation','Wan 2.1','Generate videos from text','/api/async/wan/text_to_video/2.1','video',[prompt('Video prompt')],[select('resolution','Resolution',['480p','720p'])]),
  model('wan-image-video','Video generation','Wan 2.1','Animate a single image','/api/async/wan/image_to_video/2.1','video',[media('image','First frame image','image'),prompt('Motion prompt')],[select('resolution','Resolution',['480p','720p'])]),
  model('wan-head-tail','Video generation','Wan 2.1','Create a transition between two images','/api/async/wan/head_tail_to_video/2.1','video',[media('first','First frame image','image','firstImage'),media('last','Last frame image','image','lastImage'),prompt('Transition prompt')]),
  model('dreamvideo-3-text','Video generation','DreamVideo 3.0','Configurable video length from 3 to 15 seconds','/api/async/dreamvideo_3.0/text_to_video','video',[prompt('Video prompt')],[select('resolution','Resolution',['480P','720P']),select('duration','Duration',[3,5,8,10,15],'duration',5),select('aspectRatio','Aspect ratio',['auto','16:9','9:16','1:1','4:3','3:4']),number('seed','Seed',42)],{pricing:perSecond({'480P':2,'720P':4})}),
  model('dreamvideo-3-image','Video generation','DreamVideo 3.0','Animate an image or connect first and last frames','/api/async/dreamvideo_3.0/image_to_video','video',[media('images','Reference images (up to 2)','image','images',true,{multiple:true,max:2}),prompt('Motion and scene prompt')],[select('resolution','Resolution',['480P','720P']),select('duration','Duration',[3,5,8,10,15],'duration',5),select('aspectRatio','Aspect ratio',['auto','16:9','9:16','1:1','4:3','3:4']),number('seed','Seed',42)],{pricing:perSecond({'480P':2,'720P':4})}),
  model('video-swap-face','Video editing','Video Face Swap','Replace a face in a video','/api/async/swap_face_for_video','video',[media('video','Source video','video','srcVideoUrl'),media('face','Source face','image','srcImgUrl')]),
  model('video-matting','Video editing','Video Matting','Extract a subject and alpha channel','/api/async/image_matting_process_video','video',[media('video','Source video','video','srcFileUrl')],[text('bitRate','Target bitrate (optional)','','bitRate'),toggle('removeColorSpill','Remove color spill',false)]),
  model('video-composite','Video editing','Video Composite','Composite a video with a new background','/api/async/image_matting_composite_video','video',[media('video','Source video','video','srcFileUrl'),field('alpha','Alpha video URL','text','mattingAlphaFileUrl')],[select('backgroundType','Background type',['color','image','video']),text('backgroundColor','Background color (e.g. 232d84)','232d84'),text('backgroundUrl','Background image or video URL (optional)','')]),
  model('video-watermark','Video editing','Video Watermark Removal','Remove video watermarks','/api/async/video_watermark_remover','video',[media('video','Source video','video'),prompt('Processing prompt (optional)','prompt',false)],[number('seed','Seed',-1)]),
  model('video-enhance','Video editing','Video Enhance','Upscale video and enhance detail','/api/async/video_super_resolution','video',[media('video','Source video','video','srcVideoUrl')]),
  model('video-translate','Video translation','Video Translate 2.0','Translate speech with optional lip sync','/api/async/video_translate/2.0','video',[media('video','Video to translate','video','videoUrl')],[select('sourceLanguage','Source language',['en','zh','es']),select('targetLanguage','Target language',['zh','en','es']),toggle('enableLipSync','Sync lip movements',true)]),
  model('seedance-2-5','ByteDance','Seedance 2.5','Multimodal video generation','/api/async/seedance_2.5','video',[prompt('Video prompt'),media('images','Reference image (optional)','image','images',false,{multiple:true,max:9}),media('videos','Reference video (optional)','video','videos',false,{multiple:true,max:10}),media('audios','Reference audio (optional)','audio','audios',false,{multiple:true,max:3}),media('imageUrl','First frame image (optional)','image','imageUrl',false),media('endImageUrl','Last frame image (optional)','image','endImageUrl',false)],[select('resolution','Resolution',['480p','720p','1080p']),number('duration','Duration (seconds)',5,'duration',{min:4,max:30}),select('ratio','Aspect ratio',['adaptive','16:9','9:16','1:1']),number('seed','Seed',-1),toggle('generateAudio','Generate audio',false)],{fixed:{model:'seedance-2.5'}}),
  model('seedance-2','ByteDance','Seedance 2.0','Multimodal video generation up to 4K','/api/async/seedance_2.0','video',[prompt('Video prompt'),media('images','Reference image (optional)','image','images',false,{multiple:true,max:9}),media('videos','Reference video (optional)','video','videos',false,{multiple:true,max:3}),media('audios','Reference audio (optional)','audio','audios',false,{multiple:true,max:3}),media('imageUrl','First frame image (optional)','image','imageUrl',false),media('endImageUrl','Last frame image (optional)','image','endImageUrl',false)],[select('resolution','Resolution',['480p','720p','1080p','4k']),number('duration','Duration (seconds)',5,'duration',{min:4,max:15}),select('ratio','Aspect ratio',['adaptive','16:9','9:16','1:1']),number('seed','Seed',-1),toggle('generateAudio','Generate audio',false)],{fixed:{model:'seedance-2.0'}}),
  model('seedance-2-mini','ByteDance','Seedance 2.0 Mini','Lower-cost video generation','/api/async/seedance_2.0','video',[prompt('Video prompt'),media('images','Reference image (optional)','image','images',false,{multiple:true,max:9}),media('videos','Reference video (optional)','video','videos',false,{multiple:true,max:3}),media('audios','Reference audio (optional)','audio','audios',false,{multiple:true,max:3}),media('imageUrl','First frame image (optional)','image','imageUrl',false),media('endImageUrl','Last frame image (optional)','image','endImageUrl',false)],[select('resolution','Resolution',['480p','720p']),number('duration','Duration (seconds)',5,'duration',{min:4,max:15}),select('ratio','Aspect ratio',['adaptive','16:9','9:16','1:1']),number('seed','Seed',-1),toggle('generateAudio','Generate audio',false)],{fixed:{model:'seedance-2.0-mini'}}),
  model('seedance-2-fast','ByteDance','Seedance 2.0 Fast','Fast video generation','/api/async/seedance_2.0','video',[prompt('Video prompt')],[select('resolution','Resolution',['480p','720p']),number('duration','Duration (seconds)',5,'duration',{min:4,max:15}),select('ratio','Aspect ratio',['adaptive','16:9','9:16','1:1','3:4','4:3','21:9']),number('seed','Seed',-1),toggle('generateAudio','Generate audio',false)],{fixed:{model:'seedance-2.0-fast'}}),
  model('seedance-1-5-pro','ByteDance','Seedance 1.5 Pro','Text-to-video generation','/api/async/seedance_1.5_pro','video',[prompt('Video prompt')],[select('resolution','Resolution',['480p','720p','1080p']),select('ratio','Aspect ratio',['adaptive','16:9','9:16','1:1','3:4','4:3']),number('seed','Seed',-1),toggle('generateAudio','Generate audio',false)],{fixed:{model:'seedance-1.5-pro'}}),
  model('seedream','ByteDance','Seedream','Image generation with model versions 4.0–5.0','/api/async/seedream','image',[prompt('Image prompt'),media('image','Reference image (optional)','image','image',false,{multiple:true,max:10})],[select('model','Model version',['seedream-5.0-pro','seedream-5.0-lite','seedream-4.5','seedream-4.0']),select('size','Output size',['1K','1.5K','2K']),number('seed','Seed',-1)]),
  model('nano-banana-2','Google','Nano Banana 2','Gemini 3.1 Flash image generation','/api/async/google_gemini_image','image',[prompt('Image prompt','text'),media('images','Reference image (optional)','image','images',false,{multiple:true,max:8})],[select('imageSize','Output size',['512','1K','2K','4K']),select('aspectRatio','Aspect ratio',['1:1','16:9','9:16','4:3','3:4'])],{fixed:{model:'gemini-3.1-flash-image'}}),
  model('nano-banana-pro','Google','Nano Banana Pro','High-quality Gemini 3 Pro image generation','/api/async/google_gemini_image','image',[prompt('Image prompt','text'),media('images','Reference image (optional)','image','images',false,{multiple:true,max:8})],[select('imageSize','Output size',['1K','2K']),select('aspectRatio','Aspect ratio',['1:1','16:9','9:16','4:3','3:4'])],{fixed:{model:'gemini-3-pro-image'}}),
  model('gpt-image-2','OpenAI','GPT Image 2','OpenAI image generation and editing','/api/async/gpt_image','image',[prompt('Image prompt'),media('images','Reference image (optional)','image','images',false,{multiple:true,max:4})],[number('width','Width',1024),number('height','Height',1024),select('quality','Quality',['low','medium','high']),number('n','Output count',1,'n',{min:1,max:10})]),
  model('gpt-image-2-5-flare-text','OpenAI','GPT Image 2.5 Flare','Faster GPT Image 2.5 generation','/api/async/gpt_image_2.5/flare/text_to_image','image',[prompt('Image prompt')],[number('width','Width',1024),number('height','Height',1024),select('quality','Quality',['low','medium','high','xhigh','max']),number('n','Output count',1,'n',{min:1,max:10})]),
  model('gpt-image-2-5-flare-edit','OpenAI','GPT Image 2.5 Flare','Fast reference-image editing','/api/async/gpt_image_2.5/flare/image_to_image','image',[prompt('Editing prompt'),media('images','Reference images (1–4)','image','images',true,{multiple:true,max:4})],[number('width','Width',1024),number('height','Height',1024),select('quality','Quality',['low','medium','high','xhigh','max']),number('n','Output count',1,'n',{min:1,max:10})]),
  model('gpt-image-2-5-sunburst-text','OpenAI','GPT Image 2.5 Sunburst','Higher-detail image generation','/api/async/gpt_image_2.5/sunburst/text_to_image','image',[prompt('Image prompt')],[number('width','Width',1024),number('height','Height',1024),select('quality','Quality',['low','medium','high','xhigh','max']),number('n','Output count',1,'n',{min:1,max:10})]),
  model('gpt-image-2-5-sunburst-edit','OpenAI','GPT Image 2.5 Sunburst','Detailed reference-image editing','/api/async/gpt_image_2.5/sunburst/image_to_image','image',[prompt('Editing prompt'),media('images','Reference images (1–4)','image','images',true,{multiple:true,max:4})],[number('width','Width',1024),number('height','Height',1024),select('quality','Quality',['low','medium','high','xhigh','max']),number('n','Output count',1,'n',{min:1,max:10})]),
  model('voice-clone','Audio','Voice Clone','Create a cloned voice from a sample','/api/async/voice_clone','data',[media('audio','Voice sample','audio','voiceUrl')]),
  model('tts-clone','Audio','Do TTS Clone','Synthesize speech with a cloned voice','/api/async/do_tts_clone','audio',[field('cloneId','Cloned voice ID','text','cloneId'),field('text','Text to speak','textarea','text')],[text('language','Language code','zh-CN','lan')]),
  model('tts-common','Audio','Do TTS Common','Synthesize speech with a standard voice','/api/async/do_tts_common','audio',[field('audioId','Voice ID','text','audioId'),field('text','Text to speak','textarea','text')],[text('language','Language code','zh-CN','lan')]),
  model('tts-pro','Audio','Do TTS Pro','Synthesize speech with a Pro voice','/api/async/do_tts_pro','audio',[field('audioId','Voice ID','text','audioId'),field('text','Text to speak','textarea','text')],[text('language','Language code','zh-CN','lan')]),
  model('voice-list','Audio','Voice Library','Browse standard and Pro voices',null,'data',[],[select('type','Voice type',['all','common','pro']),text('language','Language filter (optional)',''),select('timbre','Voice gender',['all','female','male'])],{utility:'voice-catalog',pricing:{unit:'free',label:'Free lookup'}})
];
